
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ESCREVER PRINT assign comment end num start string var program : start command end command : ESCREVER args args : args ',' arg args : arg arg : string"
    
_lr_action_items = {'start':([0,],[2,]),'$end':([1,5,],[0,-1,]),'ESCREVER':([2,],[4,]),'end':([3,6,7,8,10,],[5,-2,-4,-5,-3,]),'string':([4,9,],[8,8,]),',':([6,7,8,10,],[9,-4,-5,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'command':([2,],[3,]),'args':([4,],[6,]),'arg':([4,9,],[7,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> start command end','program',3,'p_program','grammar.py',27),
  ('command -> ESCREVER args','command',2,'p_command','grammar.py',31),
  ('args -> args , arg','args',3,'p_args','grammar.py',38),
  ('args -> arg','args',1,'p_args2','grammar.py',42),
  ('arg -> string','arg',1,'p_arg','grammar.py',46),
]
